[package]
name = "meson_starknet"
version = "0.1.0"
edition = "2024_07"
# See more keys at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.11.2"
openzeppelin = "1.0.0"
alexandria_bytes = "0.5.0"

[[target.starknet-contract]]
casm = true
